# Generated by Django 2.0.2 on 2019-05-21 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rating', models.FloatField(null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('roll', models.IntegerField()),
                ('feedback', models.IntegerField(blank=True, null=True)),
                ('feedback_given', models.BooleanField(default=False)),
                ('mess_off_dates', models.ManyToManyField(blank=True, related_name='choice_students', to='messapp.Date')),
                ('subscribed_mess_hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_students', to='messapp.Hostel')),
            ],
        ),
    ]
