# Generated by Django 2.0.2 on 2019-05-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='authent',
            field=models.BooleanField(default=False),
        ),
    ]
